# Generated by Django 3.2.9 on 2023-02-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('arabic_name', models.CharField(default='', max_length=35)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('saturday', models.BooleanField(blank=True, default=False, null=True)),
                ('sunday', models.BooleanField(blank=True, default=False, null=True)),
                ('monday', models.BooleanField(blank=True, default=False, null=True)),
                ('tuesday', models.BooleanField(blank=True, default=False, null=True)),
                ('wednesday', models.BooleanField(blank=True, default=False, null=True)),
                ('thursday', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.SmallIntegerField(blank=True, default=17, null=True)),
                ('end', models.SmallIntegerField(blank=True, default=19, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('isEdit', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('arabic_name', models.CharField(default='', max_length=15)),
                ('day_num', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('start', models.CharField(blank=True, max_length=5, null=True)),
                ('end', models.CharField(blank=True, max_length=5, null=True)),
                ('time', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.department')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.week')),
            ],
        ),
    ]
