# Generated by Django 3.2.9 on 2023-02-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('marriage', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('department', models.CharField(blank=True, max_length=23, null=True)),
                ('department_arabic', models.CharField(blank=True, default='', max_length=33, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('order', models.SmallIntegerField(blank=True, null=True)),
                ('timeOfArrival', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
