# Generated by Django 3.2.9 on 2023-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='husband',
            field=models.CharField(default='', max_length=30),
        ),
    ]
