# Generated by Django 3.2.9 on 2023-02-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('account', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('password', models.CharField(max_length=9)),
                ('authority', models.SmallIntegerField(blank=True, null=True)),
                ('isEdit', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
